/**
 * Place names the address normalizer may read off the end of a comma-less street line
 * ("123 MAIN ST TRUMBULL CT 06611"): Connecticut's 169 towns plus the villages and sections
 * used as mailing places around tenant zero. Words after the street that are NOT one of these
 * (or a department's own home-locality names) are never guessed to be a town — the parse is
 * marked ambiguous instead, so the match can only ever be shown flagged.
 *
 * Kept in plain spelling; addressKey.ts converts each to its compared form (North -> N).
 */
export const CT_TOWNS: readonly string[] = [
  'Andover',
  'Ansonia',
  'Ashford',
  'Avon',
  'Barkhamsted',
  'Beacon Falls',
  'Berlin',
  'Bethany',
  'Bethel',
  'Bethlehem',
  'Bloomfield',
  'Bolton',
  'Bozrah',
  'Branford',
  'Bridgeport',
  'Bridgewater',
  'Bristol',
  'Brookfield',
  'Brooklyn',
  'Burlington',
  'Canaan',
  'Canterbury',
  'Canton',
  'Chaplin',
  'Cheshire',
  'Chester',
  'Clinton',
  'Colchester',
  'Colebrook',
  'Columbia',
  'Cornwall',
  'Coventry',
  'Cromwell',
  'Danbury',
  'Darien',
  'Deep River',
  'Derby',
  'Durham',
  'East Granby',
  'East Haddam',
  'East Hampton',
  'East Hartford',
  'East Haven',
  'East Lyme',
  'East Windsor',
  'Eastford',
  'Easton',
  'Ellington',
  'Enfield',
  'Essex',
  'Fairfield',
  'Farmington',
  'Franklin',
  'Glastonbury',
  'Goshen',
  'Granby',
  'Greenwich',
  'Griswold',
  'Groton',
  'Guilford',
  'Haddam',
  'Hamden',
  'Hampton',
  'Hartford',
  'Hartland',
  'Harwinton',
  'Hebron',
  'Kent',
  'Killingly',
  'Killingworth',
  'Lebanon',
  'Ledyard',
  'Lisbon',
  'Litchfield',
  'Lyme',
  'Madison',
  'Manchester',
  'Mansfield',
  'Marlborough',
  'Meriden',
  'Middlebury',
  'Middlefield',
  'Middletown',
  'Milford',
  'Monroe',
  'Montville',
  'Morris',
  'Naugatuck',
  'New Britain',
  'New Canaan',
  'New Fairfield',
  'New Hartford',
  'New Haven',
  'New London',
  'New Milford',
  'Newington',
  'Newtown',
  'Norfolk',
  'North Branford',
  'North Canaan',
  'North Haven',
  'North Stonington',
  'Norwalk',
  'Norwich',
  'Old Lyme',
  'Old Saybrook',
  'Orange',
  'Oxford',
  'Plainfield',
  'Plainville',
  'Plymouth',
  'Pomfret',
  'Portland',
  'Preston',
  'Prospect',
  'Putnam',
  'Redding',
  'Ridgefield',
  'Rocky Hill',
  'Roxbury',
  'Salem',
  'Salisbury',
  'Scotland',
  'Seymour',
  'Sharon',
  'Shelton',
  'Sherman',
  'Simsbury',
  'Somers',
  'South Windsor',
  'Southbury',
  'Southington',
  'Sprague',
  'Stafford',
  'Stamford',
  'Sterling',
  'Stonington',
  'Stratford',
  'Suffield',
  'Thomaston',
  'Thompson',
  'Tolland',
  'Torrington',
  'Trumbull',
  'Union',
  'Vernon',
  'Voluntown',
  'Wallingford',
  'Warren',
  'Washington',
  'Waterbury',
  'Waterford',
  'Watertown',
  'West Hartford',
  'West Haven',
  'Westbrook',
  'Weston',
  'Westport',
  'Wethersfield',
  'Willington',
  'Wilton',
  'Winchester',
  'Windham',
  'Windsor',
  'Windsor Locks',
  'Wolcott',
  'Woodbridge',
  'Woodbury',
  'Woodstock',
];

/** Villages / sections used as mailing places near tenant zero (Trumbull and its neighbours). */
export const CT_VILLAGES: readonly string[] = [
  'Nichols',
  'Long Hill',
  'Trumbull Center',
  'Stepney',
  'Upper Stepney',
  'Botsford',
  'Stevenson',
  'Sandy Hook',
  'Hawleyville',
  'Devon',
  'Black Rock',
  'Southport',
  'Greens Farms',
  'Georgetown',
  'Lordship',
];
