version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /infrastructure
    schedule:
      interval: weekly
